<a href="https://colab.research.google.com/github/ShivanshSri2005/College_simple_projects/blob/main/Rock_v_Mine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
sonar_data = pd.read_excel('/content/SonarData_Normalized.xlsx', header=None)

In [ ]:
sonar_data.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.020000,0.037100,0.042800,0.020700,0.095400,0.098600,0.153900,0.160100,0.310900,0.211100,...,0.002700,0.006500,0.015900,0.007200,0.016700,0.018000,0.008400,0.009000,0.003200,Label
1,0.323009,0.221603,0.272011,0.150024,0.283033,0.666756,0.574405,0.755458,0.483045,0.394537,...,0.108417,0.218182,0.111111,0.199546,0.479487,0.389205,0.105263,0.140496,0.087760,R
2,0.182153,0.246892,0.356110,0.243699,0.230028,0.585327,0.648810,0.819405,0.817859,0.869584,...,0.319544,0.418182,0.248538,0.394558,0.615385,0.889205,0.368421,0.258953,0.166282,R
3,0.062684,0.070724,0.199737,0.034950,0.034999,0.071486,0.288149,0.269239,0.077447,0.164593,...,0.161198,0.080519,0.409357,0.179138,0.176923,0.133523,0.093822,0.107438,0.256351,R
4,0.550885,0.282898,0.153088,0.079886,0.132640,0.147003,0.318182,0.531863,0.516659,0.621479,...,0.032810,0.127273,0.277778,0.235828,0.028205,0.196023,0.102975,0.292011,0.203233,R

In [ ]:
sonar_data.shape

(208, 61)

In [ ]:
sonar_data[60].value_counts()

60
M        111
R         96
Label      1
Name: count, dtype: int64

In [ ]:
sonar_data.groupby(60).mean()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
60,,,,,,,,,,,,,,,,,,,,,
Label,0.020000,0.037100,0.042800,0.020700,0.095400,0.098600,0.153900,0.160100,0.310900,0.211100,...,0.023200,0.002700,0.006500,0.015900,0.007200,0.016700,0.018000,0.008400,0.009000,0.003200
M,0.246970,0.192645,0.161695,0.140199,0.202930,0.273217,0.338362,0.318263,0.305038,0.342802,...,0.192752,0.217026,0.289435,0.327038,0.211395,0.218295,0.213785,0.200466,0.236791,0.146183
R,0.155044,0.127014,0.112941,0.085268,0.139438,0.231118,0.298882,0.246203,0.189670,0.210904,...,0.121493,0.138849,0.238258,0.247106,0.180981,0.177778,0.210464,0.145523,0.191690,0.125938

In [ ]:
X = sonar_data.drop(columns=60, axis=1)
Y = sonar_data[60]

print(X)
print(Y)

           0         1         2         3         4         5         6   \
0    0.020000  0.037100  0.042800  0.020700  0.095400  0.098600  0.153900
1    0.323009  0.221603  0.272011  0.150024  0.283033  0.666756  0.574405
2    0.182153  0.246892  0.356110  0.243699  0.230028  0.585327  0.648810
3    0.062684  0.070724  0.199737  0.034950  0.034999  0.071486  0.288149
4    0.550885  0.282898  0.153088  0.079886  0.132640  0.147003  0.318182
..        ...       ...       ...       ...       ...       ...       ...
203  0.126844  0.145735  0.050263  0.028293  0.082678  0.410642  0.539773
204  0.227139  0.040720  0.092970  0.120304  0.175755  0.230046  0.258929
205  0.373894  0.184741  0.054205  0.055635  0.072026  0.287288  0.331169
206  0.212389  0.148736  0.156045  0.130766  0.025361  0.336469  0.387446
207  0.180678  0.153022  0.039750  0.050880  0.037281  0.063424  0.168290

           7         8         9   ...        50        51        52  \
0    0.160100  0.310900  0.211100  ...  0.023200  0.002700  0.006500
1    0.755458  0.483045  0.394537  ...  0.124502  0.108417  0.218182
2    0.819405  0.817859  0.869584  ...  0.032869  0.319544  0.418182
3    0.269239  0.077447  0.164593  ...  0.240040  0.161198  0.080519
4    0.531863  0.516659  0.621479  ...  0.155378  0.032810  0.127273
..        ...       ...       ...  ...       ...       ...       ...
203  0.361411  0.333629  0.367653  ...  0.202191  0.154066  0.241558
204  0.212348  0.141419  0.291863  ...  0.050797  0.075606  0.228571
205  0.247630  0.175181  0.345488  ...  0.154382  0.216833  0.062338
206  0.235502  0.276914  0.320463  ...  0.041833  0.111270  0.106494
207  0.296582  0.261810  0.320463  ...  0.180279  0.196862  0.322078

           53        54        55        56        57        58        59
0    0.015900  0.007200  0.016700  0.018000  0.008400  0.009000  0.003200
1    0.111111  0.199546  0.479487  0.389205  0.105263  0.140496  0.087760
2    0.248538  0.394558  0.615385  0.889205  0.368421  0.258953  0.166282
3    0.409357  0.179138  0.176923  0.133523  0.093822  0.107438  0.256351
4    0.277778  0.235828  0.028205  0.196023  0.102975  0.292011  0.203233
..        ...       ...       ...       ...       ...       ...       ...
203  0.552632  0.061224  0.248718  0.176136  0.256293  0.528926  0.348730
204  0.365497  0.129252  0.151282  0.088068  0.066362  0.168044  0.140878
205  0.119883  0.126984  0.217949  0.389205  0.308924  0.209366  0.057737
206  0.339181  0.068027  0.079487  0.088068  0.173913  0.096419  0.096998
207  0.108187  0.074830  0.146154  0.105114  0.075515  0.165289  0.251732

[208 rows x 60 columns]
0      Label
1          R
2          R
3          R
4          R
       ...
203        M
204        M
205        M
206        M
207        M
Name: 60, Length: 208, dtype: object

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

print(X.shape, X_train.shape, X_test.shape)

(208, 60) (166, 60) (42, 60)

In [ ]:
print(X_train)
print(Y_train)

           0         1         2         3         4         5         6   \
10   0.017699  0.024432  0.045007  0.066096  0.061628  0.048912  0.098214
138  0.528024  0.532790  0.542050  0.341893  0.348973  0.717012  0.682359
56   0.101032  0.041149  0.032194  0.048740  0.007608  0.077667  0.222944
71   0.015487  0.030862  0.025296  0.078222  0.117423  0.294276  0.327381
102  0.421829  0.516074  0.411629  0.342368  0.347198  0.123354  0.216180
..        ...       ...       ...       ...       ...       ...       ...
47   0.264012  0.117874  0.071288  0.039705  0.028405  0.169578  0.218615
198  0.164454  0.133733  0.133706  0.081075  0.182856  0.178447  0.229437
27   0.119469  0.126018  0.089685  0.079886  0.142785  0.113948  0.177219
163  0.042035  0.009001  0.024310  0.000713  0.089526  0.205052  0.310877
18   0.188053  0.036862  0.042707  0.052306  0.087497  0.176028  0.268669

           7         8         9   ...        50        51        52  \
10   0.047850  0.036724  0.048477  ...  0.061753  0.077033  0.298701
138  0.365380  0.057900  0.143143  ...  0.359562  0.621969  0.584416
56   0.189636  0.129424  0.198913  ...  0.047809  0.058488  0.093506
71   0.214112  0.172368  0.110825  ...  0.078685  0.158345  0.129870
102  0.136053  0.192063  0.320177  ...  0.214143  0.460770  0.275325
..        ...       ...       ...  ...       ...       ...       ...
47   0.215215  0.135940  0.098527  ...  0.065737  0.000000  0.103896
198  0.239912  0.224937  0.276705  ...  0.185259  0.125535  0.171429
27   0.127453  0.081297  0.071500  ...  0.167331  0.134094  0.303896
163  0.208159  0.281505  0.315315  ...  0.091633  0.099857  0.171429
18   0.238809  0.106471  0.201201  ...  0.044821  0.108417  0.012987

           53        54        55        56        57        58        59
10   0.122807  0.113379  0.228205  0.110795  0.000000  0.143251  0.069284
138  0.818713  0.306122  0.402564  0.494318  0.437071  0.567493  0.117783
56   0.076023  0.015873  0.107692  0.096591  0.018307  0.090909  0.062356
71   0.073099  0.068027  0.000000  0.042614  0.105263  0.063361  0.023095
102  0.228070  0.344671  0.302564  0.099432  0.224256  0.625344  0.272517
..        ...       ...       ...       ...       ...       ...       ...
47   0.040936  0.000000  0.176923  0.264205  0.116705  0.231405  0.124711
198  0.216374  0.072562  0.056410  0.071023  0.022883  0.093664  0.124711
27   0.099415  0.156463  0.307692  0.272727  0.123570  0.085399  0.030023
163  0.207602  0.063492  0.153846  0.096591  0.075515  0.030303  0.071594
18   0.023392  0.140590  0.089744  0.332386  0.295195  0.190083  0.189376

[166 rows x 60 columns]
10     R
138    M
56     R
71     R
102    M
      ..
47     R
198    M
27     R
163    M
18     R
Name: 60, Length: 166, dtype: object

In [ ]:
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, Y_train)
logreg_preds = logreg.predict(X_test)

In [ ]:
X_train_prediction = logreg.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print("Accuracy on training data: ", training_data_accuracy)

Accuracy on training data:  0.9156626506024096

In [ ]:
X_test_prediction = logreg.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print("Accuracy on test data: ", test_data_accuracy)

Accuracy on test data:  0.7619047619047619

# **Prediction**

In [ ]:
input_data = (1.32,0.8,1.88,1.41,4.36,6.68,6.09,1.31,8.99,9.22,14.45,14.75,20.87,25.58,26.03,19.85,23.94,31.34,40.77,45.29,48.93,56.66,62.34,67.41,82.8201,88.23,91.96,89.6409,75.49,67.36,64.63,50.07,36.63,22.98,13.62,21.23,23.95,26.73,28.65,20.6,16.59,26.33,25.52,16.96,14.67,12.86,9.26,7.16,3.25,2.58,1.36,0.44,0.28,0.21,0.22,0.48,1.38,1.4,0.28,0.64)
input_data_numpy = np.asarray(input_data)

input_data_reshaped = input_data_numpy.reshape(1,-1)
prediction = logreg.predict(input_data_reshaped)
print(prediction)

if(prediction[0] == 'R'):
  print('The object is a Rock')
else:
  print('The object is a Mine')

['M']
The object is a Mine